### ISSUE TITLE
Analytics endpoints

### ISSUE THREAD

**Issue by zhukovsd** [IT-job-market-analytics/rest-api#30]
- [x] Fill DB with test data (for past X days - analytics for each distinct query)
- [x] `/analytics/byQuery`
  - [x] Return dummy hardcoded date
  - [x] For the last day in the DB table, select records for distinct queries
- [x] `/analytics/history/$query?depth=30`
  - [x] Return dummy hardcoded date
  - [x] Select data for the last `$depth` days, order ASC by date

`/analytics/byQuery` response:
```
[
  {
    "query": "java",
    "vacancyCount": 123,
    "averageSalary": 12.34
  }
]
```

`/analytics/history/$query?depth=30` response:
```
[
  {
    "date": "01.01.2023",
    "vacancyCount": 123,
    "averageSalary": 12.34
  }
]
```

**Comment by DLISM** [comment]
--add-opens java.base/java.time=ALL-UNNAMED

добавил в VM Options чтобы маппер работал
