### ISSUE TITLE
Signing in

### ISSUE THREAD

**Issue by zhukovsd** [IT-job-market-analytics/rest-api#8]
- [x] Controller for `POST /auth/signin`
- [x] Service class for validating username and password
- [x] Generate JWT token on successful authorization
- [x] Set JWT token as response cookie or response body 
- [x] Invalid username, invalid password - Unauthorized 401
- [x] Success - OK 200
- [x] Test controller requiring authorization (403 if no token, 200 if a valid token)
- [x] `.http` file with requests to `/auth/signin` controller

Example error response body:
```
{
  "message": "Invalid password"
}
```

**Comment by zhukovsd** [comment]
Example - https://www.bezkoder.com/spring-boot-jwt-authentication/

**Comment by DLISM** [comment]
Не получилось сохранить роли пользователя. 
Не понял как в Data JDBC сохранят каскадные записи

**Comment by zhukovsd** [comment]
Роли нам не нужны, у нас у всех юзеров одна базовая роль.
